### ISSUE TITLE
No such file or directory: '.../venv/bin/python3'

### ISSUE THREAD

**Issue by karmingc** [CircleCI-Public/cimg-python#130]
I was previously using `circleci/python:3.8.10` and found no issues with my build, both on PRs and on main branch builds.

```yml
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: install requirements
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
```

As part of migrating from python 3.8 to python 3.10x on my web application, I updated to `cimg/python:3.10.4` and there were no issues with PRs - the circleci went through successfully. However, once merged to main branch, it started failing with

```sh
#!/bin/bash -eo pipefail
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt

Error: [Errno 2] No such file or directory: '/home/circleci/<project name>/venv/bin/python3'

Exited with code exit status 1
CircleCI received exit code 1

```

I'm suspecting some issues with caches, but i'm unsure how to resolve.

When i tried to SSH into the PR, i can see python3 in blue cyan, which i'm assuming is a symlink.

![Screen Shot 2022-04-05 at 5 07 57 PM](https://user-images.githubusercontent.com/41309630/161849385-904db743-4594-41fc-8b81-03a1ce41add9.png)

However, once merged, python3 is in red...

![Screen Shot 2022-04-05 at 5 08 10 PM](https://user-images.githubusercontent.com/41309630/161849408-0fba1ff1-7cd7-425e-9993-9dfd5bdddf26.png)

Any ideas?
