### ISSUE TITLE
Bug Report: pyenv shell integrations not enabled

### ISSUE THREAD

**Issue by cjw296** [CircleCI-Public/cimg-python#220]
**Describe the bug**

While pyenv is used to build these images, the [shell integrations](https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv) are missing.

What this means is that if you install a package that provides a console script, such as pytest, the console script will not be available in your Circle CI jobs.

**To Reproduce**

A job with the following steps will do it:

```yaml
      - run:
          name: "Install PyTest"
          command: "python -m pip install pytest"
      - run:
          name: "Run PyTest"
          command: "pytest --help"
```

**Expected behavior**

I'd expect the `pytest` help message to be printed.

**Workarounds**

I'm going to try `python -m pytest` instead.
