### ISSUE TITLE
3.9.X variants missing python3.9 packages in /usr/local/lib

### ISSUE THREAD

**Issue by nbialostosky** [CircleCI-Public/cimg-python#94]
At the moment the `cimg` 3.9.X variants of Python don't contain the `python3.9` site-packages. As an example, here is the contents of `/usr/local/lib` on `cimg/python:3.9.6`:

```
ls -la /usr/local/lib
total 0
drwxr-xr-x 1 root root  23 Jun 29 17:14 .
drwxr-xr-x 1 root root  30 Mar 25 16:58 ..
drwxrwsr-x 4 root staff 48 Jun 29 17:15 python2.7
drwxrwsr-x 3 root staff 27 Apr  2 00:16 python3.8
```

Here is `circleci/python:3.9.6` you'll see `python3.9` is present:

```
ls -la /usr/local/lib
total 18512
drwxr-xr-x 1 root root       23 Aug 17 15:38 .
drwxr-xr-x 1 root root       28 Aug 16 00:00 ..
lrwxrwxrwx 1 root root       19 Aug 17 15:38 libpython3.9.so -> libpython3.9.so.1.0
-rwxr-xr-x 1 root root 18939312 Aug 17 15:38 libpython3.9.so.1.0
-rwxr-xr-x 1 root root    15528 Aug 17 15:38 libpython3.so
drwxr-xr-x 2 root root       96 Aug 17 15:38 pkgconfig
drwxr-xr-x 1 root root      266 Aug 17 15:38 python3.9
```

To replicate:

```
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.6
    steps:
      - run: ls -la /usr/local/lib
  test:
    docker:
      - image: cimg/python:3.9.6
    steps:
      - run: ls -la /usr/local/lib

workflows:
  build-and-test:
    jobs:
      - build
      - test
```
